import type { FastifyInstance, FastifyRequest } from "fastify";
import { and, desc, eq, like, or } from "drizzle-orm";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { db } from "../../db/client.js";
import { bulkEnquiries, cartItems, carts, categories, inventoryMovements, orderItems, orders, products, savedProducts, users, variants } from "../../db/schema.js";
import { AuthRequest, availability, cartResponse, ensureCart, findCategory, findProduct, inventoryUnits, login, now, pageParams, productInput, publicProduct, serializeOrder, slugify, adminProducts } from "../../shared/context.js";

export async function registerCartControllers(app: FastifyInstance) {
  app.get("/cart", { preHandler: app.authenticate }, async (request) => cartResponse((request as AuthRequest).user.id));
  app.post("/cart/items", { preHandler: app.authenticate }, async (request, reply) => { const input = z.object({ variantId: z.string(), quantity: z.number().int().positive(), sellAsPieces: z.boolean().default(false) }).parse(request.body); const v = (await db.select().from(variants).where(eq(variants.id, input.variantId)).limit(1))[0]; if (!v || !v.active || (input.sellAsPieces && v.sellableType !== "pack")) return reply.code(409).send({ code: "UNAVAILABLE", message: "Product option is unavailable.", details: null }); const available = input.sellAsPieces ? inventoryUnits(v) : v.inventoryPacks; if (input.quantity > available) return reply.code(409).send({ code: "INSUFFICIENT_INVENTORY", message: "Requested quantity is above availability.", details: null }); const userId = (request as AuthRequest).user.id; const cart = await ensureCart(userId); const existing = (await db.select().from(cartItems).where(and(eq(cartItems.cartId, cart.id), eq(cartItems.variantId, v.id), eq(cartItems.sellAsPieces, input.sellAsPieces))).limit(1))[0]; if (existing) await db.update(cartItems).set({ quantity: existing.quantity + input.quantity, updatedAt: now() }).where(eq(cartItems.id, existing.id)); else await db.insert(cartItems).values({ id: randomUUID(), cartId: cart.id, variantId: v.id, quantity: input.quantity, sellAsPieces: input.sellAsPieces, createdAt: now(), updatedAt: now() }); return cartResponse(userId); });
  app.patch("/cart/items", { preHandler: app.authenticate }, async (request) => { const input = z.object({ variantId: z.string(), quantity: z.number().int().positive(), sellAsPieces: z.boolean().default(false) }).parse(request.body); const cart = await ensureCart((request as AuthRequest).user.id); await db.update(cartItems).set({ quantity: input.quantity, updatedAt: now() }).where(and(eq(cartItems.cartId, cart.id), eq(cartItems.variantId, input.variantId), eq(cartItems.sellAsPieces, input.sellAsPieces))); return cartResponse((request as AuthRequest).user.id); });
}
