import type { FastifyInstance, FastifyRequest } from "fastify";
import { and, desc, eq, like, or } from "drizzle-orm";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { db } from "../../db/client.js";
import { bulkEnquiries, cartItems, carts, categories, inventoryMovements, orderItems, orders, products, savedProducts, users, variants } from "../../db/schema.js";
import { AuthRequest, availability, cartResponse, ensureCart, findCategory, findProduct, inventoryUnits, login, now, pageParams, productInput, publicProduct, serializeOrder, slugify, adminProducts } from "../../shared/context.js";
import { writeAudit } from "../audit/service.js";

export async function registerCategoryControllers(app: FastifyInstance) {
  app.get("/admin/categories", { preHandler: app.requireAdmin }, async (request) => { const q = pageParams.parse(request.query); const rows = await db.select().from(categories).where(q.search ? like(categories.name, `%${q.search}%`) : undefined); return rows.slice((q.page - 1) * q.pageSize, q.page * q.pageSize); });
  app.post("/admin/categories", { preHandler: app.requireAdmin }, async (request, reply) => { const input = z.object({ name: z.string().min(2), description: z.string().optional(), active: z.boolean().default(true) }).parse(request.body); const category = { id: randomUUID(), name: input.name, slug: slugify(input.name), description: input.description || null, active: input.active, createdAt: now(), updatedAt: now() }; await db.insert(categories).values(category); await writeAudit(request, { action: "category.created", entityType: "category", entityId: category.id, after: category }); return reply.code(201).send(category); });
  app.patch("/admin/categories/:id", { preHandler: app.requireAdmin }, async (request, reply) => { const input = z.object({ name: z.string().min(2).optional(), description: z.string().optional(), active: z.boolean().optional() }).parse(request.body); const id = z.object({ id: z.string() }).parse(request.params).id; const before = (await db.select().from(categories).where(eq(categories.id, id)).limit(1))[0]; if (!before) return reply.code(404).send({ code: "NOT_FOUND", message: "Category not found.", details: null }); const updated = (await db.update(categories).set({ ...input, slug: input.name ? slugify(input.name) : undefined, updatedAt: now() }).where(eq(categories.id, id))); if (!updated[0].affectedRows) return reply.code(404).send({ code: "NOT_FOUND", message: "Category not found.", details: null }); const after = (await db.select().from(categories).where(eq(categories.id, id)).limit(1))[0]; await writeAudit(request, { action: "category.updated", entityType: "category", entityId: id, before, after }); return after; });
  app.delete("/admin/categories/:id", { preHandler: app.requireAdmin }, async (request, reply) => { const id = z.object({ id: z.string() }).parse(request.params).id; const before = (await db.select().from(categories).where(eq(categories.id, id)).limit(1))[0]; if (!before) return reply.code(404).send({ code: "NOT_FOUND", message: "Category not found.", details: null }); const inUse = (await db.select().from(products).where(eq(products.categoryId, id)).limit(1)).length; if (inUse) return reply.code(409).send({ code: "CATEGORY_IN_USE", message: "Reassign products before deleting this category.", details: null }); await db.delete(categories).where(eq(categories.id, id)); await writeAudit(request, { action: "category.deleted", entityType: "category", entityId: id, before }); return { ok: true }; });
}
